name: Build Push Prune

on:
  pull_request_target:
    types:
      - closed
  schedule:
    - cron: "0 6 * * *"  # 6am everyday.

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  BASE_IMAGE_NAME: pangtao22/quasistatic_simulator_base
  IMAGE_NAME: pangtao22/quasistatic_simulator

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune base
        uses: vlaurin/action-ghcr-prune@v0.5.0
        if: github.event.pull_request.merged == true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          container: ${{ env.BASE_IMAGE_NAME }}
          dry-run: false # Dry-run first, then change to `false`
          keep-last: 10
          prune-untagged: true
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          container: ${{ env.IMAGE_NAME }}
          dry-run: false # Dry-run first, then change to `false`
          keep-younger-than: 3 # days
          prune-untagged: true
